config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  ActiveAdmin.routes(self)
  mount Attachinary::Engine => "/attachinary"

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#home'
    get '/lessons', to: 'pages#lessons', as: :all_lessons
    get '/teachers', to: 'pages#teachers', as: :all_teachers
    get '/list/:id', to: 'messages#list', as: :conversation

    devise_for :users, skip: :omniauth_callbacks
    resources :users, only: [:show, :update] do
      #get '/list', to: 'messages#list', as: :conversation
    end
    resources :messages, only: [:index, :new, :create]

    resources :teachers, only: [:new, :update, :show] do
      resources :messages, only: [:create]
      member do
        get 'lessons'
      end
    end

    resources :bookings, only: [:edit, :update, :show] do
      resources :payments, only: [:new, :create]
        member do
          delete 'cancel'
        end
      member do
        get 'cancel'
      end
      collection do
        get 'my_teacher_index'
        get 'my_student_index'
      end
    end

    resources :lessons, only: [:show, :new, :create, :edit, :update] do
      member do
        get 'cancel'
      end
      resources :bookings, only: [:new, :create]
    end
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
  monetize :amount_cents
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :cancel]

  after_action :verify_authorized, except: [:my_student_index, :my_teacher_index]
  after_action :verify_policy_scoped, only: [:my_teacher_index, :my_student_index]

  def my_student_index
    @bookings = policy_scope(Booking).bookings
    @future_bookings = []
    @past_bookings =[]
    @bookings.each do |booking|
      if booking.lesson.start_date >= DateTime.now
        @future_bookings << booking
      else
        @past_bookings << booking
      end
    end
    @future_bookings = @future_bookings.sort_by {|obj| obj.lesson.start_date}
    @past_bookings = @past_bookings.sort_by {|obj| obj.lesson.start_date}
  end

  def my_teacher_index
    @bookings = policy_scope(Booking).lessons.collect(&:bookings).flatten.uniq
  end

  def show
  end

  def create
    @lesson = Lesson.find(params[:lesson_id])
    @booking = current_user.bookings.build()
    authorize @booking
    if check_availability == true
      @booking.lesson = @lesson
      @booking.lesson_sku = @lesson.sku
      @booking.update_attributes(lesson_sku: @lesson.sku, amount: @lesson.price, payment_state: 'pending')
      if @booking.save
        # LessonMailer.booking_confirmation(@booking).deliver_now
        redirect_to new_booking_payment_path(@booking)
      else
        flash[:alert] = t('.flash_alert_not_saved')
      end
    else
      flash[:alert] = t('.flash_alert_full')
      redirect_to lessons_path
    end
  end

  def edit
  end

  def update ##pas besoin sauf si on gère le nombre de place par booking
    if @booking.update(booking_params)
      redirect_to my_student_index_bookings_path
    else
      flash[:alert] = t('.flash_alert')
    end
  end

  def cancel

      Stripe.api_key = ENV['STRIPE_SECRET_KEY']
      refund = Stripe::Charge.retrieve(@booking.payment['id'])
      refund.refunds.create(:amount => @booking.payment['amount'])

      #update booking.payment
      @booking.update(payment: refund.to_json, payment_state: 'refunded')
      @booking.update_attribute(:status, 'cancelled')
      redirect_to my_student_index_bookings_path
  end

  private

  def check_availability
    @lesson = Lesson.find(params[:lesson_id])
    @lesson.bookings.count < @lesson.max_students
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:review_content, :review_rating)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_booking.html.erb
<p><b>Review id:</b> <%= @booking.id %></p>

<p><b>Review Content:</b> <%= @booking.review_content %></p>

<p><b>Review Rating:</b> <%= @booking.review_rating %></p>

<%= link_to 'Add review', lesson_booking_path(@booking) %>

app/views/bookings/_form_booking.html.erb
<%= simple_form_for([@lesson, @booking]) do |f| %>
  <%= f.error_notification %>
  <div class="text-center">
  <%= f.button :submit %></div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Add a review</h1>

<%= simple_form_for @booking do |f| %>
  <%= f.error_notification %>
  <%= f.input :review_content %>
  <%= f.input :review_rating %>
  <div class="text-center">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/my_student_index.html.erb
<section id="home" class="home-newsletter">
    <div class="row no-margin">
        <div class="col-sm-12 center-title">
            <h2><i class="fa fa-calendar"></i> <%= t('.my_bookings') %></h2>
        </div>
        <div class="col-sm-12 text-center">
          <%= link_to t('.new_lesson'), all_lessons_path, class:"btn btn-lg btn-skin btn-radius" %>
        </div>
    </div>
</section>

<section class="blog" id="search">
  <div class="container">

    <div class="row">
      <% if @bookings == [] %>
      <div class="col-sm-8  col-sm-offset-2 text-center wow animated bounceIn">
        <p> <%= t('.no_booking')  %> </p>
      </div>
      <% end %>
    </div>

    <% if @future_bookings != [] %>
    <div class="row">
      <div class="col-sm-12 center-title wow animated bounceIn padded-custom">
        <h2><%= t('.next_bookings') %></h2>
      </div>
        <% @future_bookings.each do |booking| %>
      <div class="col-sm-4">
        <div class="item" id='search-item-list'>
          <h3 class="home"><a href='/lessons/<%=booking.lesson.id%>'><%= booking.lesson.name%></a></h3>
          <ul class="list-inline">
            <li><a href="#"><i class="ti-user"></i>By <%= booking.lesson.teacher.first_name %> </a></li>
            <li><i class="ti-calendar"></i><%= booking.lesson.start_date.to_time.to_formatted_s(:short) %></li>
            <li><a href="#"><i class="ti-comments"></i><%= booking.lesson.price %> €</a></li>
          </ul>
          <% if booking.status == 'confirmed' %>
          <a href="/bookings/<%= booking.id%>/cancel" class="btn btn-default card"> Annuler </a>
          <% else %>
          <a href="#" class="btn btn-black card"> Annulé </a>
          <a href="/lessons/<%= booking.lesson.id%>" class="btn btn-default card"> Se réinscrire </a>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>

    <% if @past_bookings != [] %>
    <div class="row">
      <div class="col-sm-12 center-title wow animated bounceIn padded-custom">
        <h2><%= t('.past_bookings') %></h2>
      </div>
      <% @past_bookings.each do |booking| %>
      <div class="col-sm-4">
        <div class="item" id='search-item-list'>
          <h3 class="home"><a href="/lessons/<%=booking.lesson.id%>"> <%= booking.lesson.name%></a></h3>
          <ul class="list-inline">
            <li><a href="#"><i class="ti-user"></i>By <%= booking.lesson.teacher.first_name %> </a></li>
            <li><i class="ti-calendar"></i><%= booking.lesson.start_date.to_time.to_formatted_s(:short) %></li>
            <li><a href="#"><i class="ti-comments"></i><%= booking.lesson.price %> €</a></li>
          </ul>
          <a href="#" class="btn btn-default card"> Noter ce cours </a>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>

  </div>
</section>

app/views/bookings/my_teacher_index.html.erb
<% @bookings.each do |booking| %>
booking: <%= booking.id %> <br>
lesson: <%= booking.lesson_id %> <br>
<% end %>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/bookings/show.html.erb
<ul>
  <li>Booking_id: <%= @booking.id %></li>
  <li>Lesson_id: <%= @booking.lesson_id %></li>
  <li>Payment status: <%= @booking.payment_state %></li>
  <li>Item: <%= @booking.lesson_sku %></li>
  <li>Amount: <%= humanized_money_with_symbol(@booking.amount) %></li>
  <li>Review: <%= @booking.review_content %></li>
  <li>Rating: <%= @booking.review_rating %></li>
<ul>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>