config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  ActiveAdmin.routes(self)
  mount Attachinary::Engine => "/attachinary"

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#home'
    get '/lessons', to: 'pages#lessons', as: :all_lessons
    get '/teachers', to: 'pages#teachers', as: :all_teachers
    get '/list/:id', to: 'messages#list', as: :conversation

    devise_for :users, skip: :omniauth_callbacks
    resources :users, only: [:show, :update] do
      #get '/list', to: 'messages#list', as: :conversation
    end
    resources :messages, only: [:index, :new, :create]

    resources :teachers, only: [:new, :update, :show] do
      resources :messages, only: [:create]
      member do
        get 'lessons'
      end
    end

    resources :bookings, only: [:edit, :update, :show] do
      resources :payments, only: [:new, :create]
        member do
          delete 'cancel'
        end
      member do
        get 'cancel'
      end
      collection do
        get 'my_teacher_index'
        get 'my_student_index'
      end
    end

    resources :lessons, only: [:show, :new, :create, :edit, :update] do
      member do
        get 'cancel'
      end
      resources :bookings, only: [:new, :create]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bookings
  has_many :messages
  after_create :send_welcome_email
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :photo, PhotoUploader
  serialize :yoga_type, Array

  def teacher?
    type == 'Teacher'
  end

  def set_as_teacher
    self.type = 'Teacher'
    save
  end

  def set_as_user
    self.type = nil
  end

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.remote_photo_url = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
      #fail
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  after_action :verify_authorized

  def show
    authorize User.find(params[:id])
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    # if @user.teacher?
    #   if @user.update(teacher_params)
    #     redirect_to user_path
    #   else
    #     flash[:alert] = t('.flash_alert')
    #   end
    # else
    if @user.update(user_params)
      redirect_to user_path
    else
      flash[:alert] = t('.flash_alert')
      render :show
    end
  end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :email, :street, :city, :zipcode, :country, :phone, :gender, :birth_date, :photo, :photo_cache, :level, :address, :street_number, yoga_type: [])
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def show_avatar
    if current_user.photo?
      image_tag current_user.photo, class: "avatar avatar-large"
    else
      cl_image_tag("avatar.png", class: "avatar avatar-large")
    end
  end

  def show_card_avatar(user)
    if user.photo?
      image_tag user.photo, class:"card-user avatar avatar-large"
    else
      cl_image_tag("avatar.png", class: "avatar avatar-large")
    end
  end

  def show_big_avatar(user)
    if user.photo?
      image_tag user.photo, class:"card-user avatar avatar-mega-large"
    else
      cl_image_tag("avatar.png", class: "avatar avatar-mega-large")
    end
  end
end

app/views/users/_form_user.html.erb
<%= simple_form_for(@user, html: { class: 'assan-contact'}) do |f| %>
  <%= f.error_notification %>
<div class="col-sm-3 center-title profil_avatar">
  <div class="col-sm-12" id="avatar_profil">
    <%= show_big_avatar(@user) %>
  </div>
  <div class="col-sm-12">
    <%= f.input :photo, label: false %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>
</div>
<div class="col-sm-6">
  <div class="wrapper-grey">
    <div class="row">
      <div class="col-sm-12">
        <%= f.input :first_name, input_html: { class: 'form-control'} %>
      </div>
      <div class="col-sm-12">
        <%= f.input :last_name, input_html: { class: 'form-control'} %>
      </div>
      <div class="col-sm-12">
        <%= f.input :email, input_html: { class: 'form-control'} %>
      </div>
      <div class="col-sm-12">
        <div class="form-group">
          <div class='input-group date' id='datetimepicker1'>
            <div class="col-sm-8 no-padding">
              <%= f.input :birth_date, as: :string, input_html: { class: 'form-control'} %>
            </div>
            <div class="col-sm-4 datepicker-btn-padding">
              <span class="input-group-addon btn btn-skin btn-radius btn-lg">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-12 checkbox_container">
        <%= f.input :gender, collection: [:male, :female]%>
      </div>
      <div class="col-sm-12">
        <%= f.input :phone, input_html: { class: 'form-control'} %>
      </div>
      <div class="col-sm-12">
        <%= f.input :yoga_type, as: :check_boxes, collection: ['Ashtanga Vinyasa Yoga', 'Iyengar Yoga', 'Vinyasa Yoga', 'Hatha Yoga', 'Yoga Chamanique', 'Yin Yoga', 'Pranayama'], item_wrapper_class: 'inline', input_html: { multiple: true } %>
      </div>
      <div class="col-sm-12">
        <%= f.input :level, collection: [:beginner, :confirmed, :expert], input_html: { class: 'form-control'}%>
      </div>
      <div class="col-sm-12">
        <%= f.input :address, input_html: { id: 'user_input_autocomplete_address' } %>
      </div>
      <div class="col-sm-12">
        <%= f.input :street_number, input_html: { id: 'street_number', class: 'form-control'}, as: :hidden %>
      </div>
      <div class="col-sm-12">
        <%= f.input :street, input_html: { id: 'route', class: 'form-control'}, as: :hidden %>
      </div>
      <div class="col-sm-12">
        <%= f.input :city, input_html: { id: 'locality', class: 'form-control'}, as: :hidden %>
      </div>
      <div class="col-sm-12">
        <%= f.input :zipcode, input_html: { id: 'postal_code', class: 'form-control'}, as: :hidden %>
      </div>
      <% if @user.teacher? %>
      <p> Vos informations en tant que professeur </p>
      <div class="col-sm-12">
        <%= f.input :experience, input_html: { class: 'form-control'} %>
      </div>
      <div class="col-sm-12">
        <%= f.input :description, input_html: { class: 'form-control'} %>
      </div>
      <div class="col-sm-12">
      <%= f.input :photos, as: :attachinary %>
      </div>
      <% end %>
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <div class="data-status animated fadeInDown"></div> <!-- data submit status -->
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12 text-center">
          <%= f.button :submit, class:'btn btn-lg btn-skin btn-radius margin-b-20' %>
        </div>
      </div>
      <% end %>
  </div>
</div>

  <% content_for(:js) do %>
  <%= javascript_tag do %>
  $(function () {
    $('#datetimepicker1').datetimepicker({
              viewMode: 'years',
              format: 'DD/MM/YYYY'
                });
  });
  <% end %>
  <% end %>

app/views/users/show.html.erb
<section id="home" class="home-newsletter">
    <div class="row no-margin">
        <div class="col-sm-12 center-title">
          <h2><i class="fa fa-user"></i><%= t(".profile", default: "Profile") %></h2>
        </div>
    </div>
</section>

<section id="contact" class="contact-section">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 center-title">
      </div>
    </div>
    <div class="row">
      <%= render 'form_user' %>
    </div>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3 center-title">
        <% if @user.teacher? %>
        <div class="col-sm-6 center-title">
          <%= link_to t('.view_public_profile'), teacher_path(@user), class:"link_profile" %>
        </div>
        <div class="col-sm-6 center-title">
          <%= link_to t('.my_lessons'), lessons_teacher_path(@user), class:"link_profile" %>
        </div>
        <% else %>
        <div class="col-sm-12 center-title">
          <%= link_to t('.become_teacher'), new_teacher_path, class:"link_profile" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/upgrade_to_teacher.html.erb
<%= render 'teachers/form_teacher' %>