config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  ActiveAdmin.routes(self)
  mount Attachinary::Engine => "/attachinary"

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#home'
    get '/lessons', to: 'pages#lessons', as: :all_lessons
    get '/teachers', to: 'pages#teachers', as: :all_teachers
    get '/list/:id', to: 'messages#list', as: :conversation

    devise_for :users, skip: :omniauth_callbacks
    resources :users, only: [:show, :update] do
      #get '/list', to: 'messages#list', as: :conversation
    end
    resources :messages, only: [:index, :new, :create]

    resources :teachers, only: [:new, :update, :show] do
      resources :messages, only: [:create]
      member do
        get 'lessons'
      end
    end

    resources :bookings, only: [:edit, :update, :show] do
      resources :payments, only: [:new, :create]
        member do
          delete 'cancel'
        end
      member do
        get 'cancel'
      end
      collection do
        get 'my_teacher_index'
        get 'my_student_index'
      end
    end

    resources :lessons, only: [:show, :new, :create, :edit, :update] do
      member do
        get 'cancel'
      end
      resources :bookings, only: [:new, :create]
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible alert-blue" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <%= link_to root_path, class: "navbar-wagon-brand" do %>
          <%= image_tag "logo.png" %>
        <% end %>
      </div>
      <div class="col-xs-3">
        <h3> <%= t('.social_links') %> </h3>
        <ul class="list-inline">
          <li><a href=""><i class="fa fa-instagram"></i></a></li>
          <li><a href=""><i class="fa fa-facebook"></i></a></li>
          <li><a href=""><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-3">
        <h3> <%= t('.contact') %> </h3>
        <ul>
          <li> contact@yogastory.fr </li>
        </ul>
      </div>
      <div class="col-xs-3">
        <h3> <%= t('.help') %> </h3>
        <ul>
          <li> <%= t('.faq') %> </li>
          <li> <%= t('.cgv') %> </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer_theme.html.erb
<!--footer start-->
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4 margin-b-30">
                        <h2>Yoga Story</h2>
                        <p>
                            Yoga for everyone. Everywhere
                        </p>
                        <div class="space-20"></div>
                        <a href='/lessons' class="btn btn-skin btn-radius btn-lg"><%= t('.try') %></a>
                    </div>
                     <div class="col-sm-4 margin-b-30">
                        <h2><%= t('.contact') %></h2>
                        <ul class="list-unstyled clearfix">
                            <li class="clearfix">
                                <i class="fa fa-map-marker"></i>
                                <span>12ter, rue des Tours - 59000 LILLE</span>
                            </li>
                             <li class="clearfix">
                                <i class="fa fa-envelope-o"></i>
                                <span><a href='#'>contact@yogastory.fr</a></span>
                            </li>
                             <li class="clearfix">
                                <i class="fa fa-phone"></i>
                                <span>+01 1234 434-345</span>
                            </li>
                        </ul>
                    </div><!--col4 end-->
                     <div class="col-sm-4 margin-b-30">
                        <h2><%= t('.social_links') %></h2>
                        <ul class="list-inline clearfix">
                            <li><a href='#'><i class="fa fa-facebook-official"></i></a></li>
                            <li><a href='#'><i class="fa fa-twitter"></i></a></li>
                            <li><a href='#'><i class="fa fa-google-plus"></i></a></li>
                            <li><a href='#'><i class="fa fa-linkedin"></i></a></li>
                            <li><a href='#'><i class="fa fa-youtube"></i></a></li>
                        </ul>
                    </div><!--col4 end-->
                </div><!--row end-->
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <div class="footer-bottom">
                             <!-- <ul class="list-inline">
                            <li><a href='#'>Home</a></li>
                            <li><a href='#'>News</a></li>
                            <li><a href='#'>Help</a></li>
                            <li><a href='#'>Terms</a></li>
                            <li><a href='#'>Privacy</a></li>
                        </ul> -->
                        <span>&copy; Copyright 2016 - Made with <i class="fa fa-heart"></i> @ LeWagon</span>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!--footer end-->

app/views/shared/_navbar_theme.html.erb
 <header class="navbar navbar-default header-v2 navbar-fixed-top">
     <div class="container">
        <div class="navbar-header scroll-to">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <%= link_to root_path, class: "navbar-brand" do %>
                Yoga Story
            <% end %>   
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav scroll-to navbar-nav">
                <% if user_signed_in? %>
                  <li class="active"> <%= link_to t(".profile", default: "Profile"), user_path(current_user) %>
                  </li>

            <ul class="nav scroll-to navbar-nav">
                  <li><%= link_to destroy_user_session_path, method: :delete do %>
                    <i><%= t(".sign_out", default: "Log out") %></i>
                  </li>
                  <% end %>
            </ul>

                <% if current_user.teacher? %>
                  <li><%= link_to t(".offer", default: "My classes proposal"), lessons_teacher_path(current_user) %>
                  </li>
                
            <% else %>

                  <li><%= link_to t(".lessons", default: "My lessons"), my_student_index_bookings_path %>
                  <% end %>
            </ul>

                
            <% else %>

                  <li class="active"><%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path %>
                  </li>

            <% end %>
                
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</header>