config/routes.rb
Rails.application.routes.draw do

  get 'payments/new'

  ActiveAdmin.routes(self)
  mount Attachinary::Engine => "/attachinary"

  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#home'
    get '/lessons', to: 'pages#lessons', as: :all_lessons
    get '/teachers', to: 'pages#teachers', as: :all_teachers
    get '/list/:id', to: 'messages#list', as: :conversation

    devise_for :users, skip: :omniauth_callbacks
    resources :users, only: [:show, :update] do
      #get '/list', to: 'messages#list', as: :conversation
    end
    resources :messages, only: [:index, :new, :create]

    resources :teachers, only: [:new, :update, :show] do
      resources :messages, only: [:create]
      member do
        get 'lessons'
      end
    end

    resources :bookings, only: [:edit, :update, :show] do
      resources :payments, only: [:new, :create]
        member do
          delete 'cancel'
        end
      member do
        get 'cancel'
      end
      collection do
        get 'my_teacher_index'
        get 'my_student_index'
      end
    end

    resources :lessons, only: [:show, :new, :create, :edit, :update] do
      member do
        get 'cancel'
      end
      resources :bookings, only: [:new, :create]
    end
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :teacher, class_name: 'User', foreign_key: 'teacher_id'
  has_many :bookings
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  validates_presence_of :start_date, :hours, :min_students, :max_students, :price, :name, :description, :address
  monetize :price_cents
  validate :start_date_in_future
  mount_uploader :photo, PhotoUploader

  def start_date_in_future
    if self.start_date < DateTime.now
      errors.add(:start_date, "Start date should be in future")
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :cancel]
  after_action :verify_authorized, except: [:show]

  def index
    @lessons = policy_scope(Lesson)
  end

  def show
    @booking = current_user.bookings.new
    authorize @booking
    @message = current_user.messages.new
    authorize @message
    @marker = Gmaps4rails.build_markers(@lesson) do |lesson, marker|
      marker.lat lesson.latitude
      marker.lng lesson.longitude
      marker.infowindow lesson.name
    end
  end

  def new
    @lesson = current_user.lessons.new
    authorize @lesson
  end

  def create
    @teacher = current_user
    @lesson = @teacher.lessons.build(lesson_params)
    authorize @lesson
    if @lesson.save
      LessonMailer.creation_confirmation(@lesson).deliver_now
      redirect_to lessons_teacher_path(current_user)
    else
      flash[:alert] = t('.flash_alert')
      render :new
    end
  end

  def edit
  end

  def update
    if params[:lesson][:start_date] != "" && @lesson.update(lesson_params)
      @lesson.update_attribute(:status, 'confirmed')
      redirect_to lessons_teacher_path(current_user)
    else
      flash[:alert] = t('.flash_alert')
      render :edit
    end
  end

  def cancel
    @lesson.update_attribute(:status, 'cancelled')
    redirect_to lessons_teacher_path(current_user)
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
    authorize @lesson
  end

  def lesson_params
    parameters = params.require(:lesson).permit(:name, :start_date, :hours, :minutes, :address, :street_number, :street, :city, :zip_code, :min_students, :max_students, :description, :price, :location_name)
    if /PM/.match(parameters[:start_date])
      to_add = 12.0
    else
      to_add = 0
    end
    parameters[:start_date] =  DateTime.strptime(parameters[:start_date], "%m/%d/%Y %H:%M") + (to_add / 24) - (2.0 / 24)
    parameters
  end

end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form_lesson.html.erb
<%= simple_form_for(@lesson, html: { class: 'assan-contact'}) do |f| %>
<%= f.error_notification %>
<div class="row">
  <div class="col-sm-12">
    <%= f.input :name, input_html: { class: 'form-control'} %>
  </div>
  <div class="col-sm-12">
    <div class="form-group">
      <div class='input-group date' id='datetimepicker1'>
      <div class="col-sm-8 no-padding">
        <%= f.input :start_date, as: :string, input_html: { class: 'form-control'} %>
        </div>
        <div class="col-sm-4 datepicker-btn-padding">
        <span class="input-group-addon btn btn-skin btn-radius btn-lg">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
        </div>
      </div>
    </div>
  </div>
  <p> Durée du cours </p>
  <div class="col-sm-6">
    <%= f.input :hours, collection: 0..4, input_html: { class: 'form-control'} %>
  </div>
  <div class="col-sm-6">
    <%= f.input :minutes, collection: [0, 15, 30, 45], input_html: { class: 'form-control'} %>
  </div>
  <p> Nombre de participants </p>
  <div class="col-sm-6">
    <%= f.input :min_students, input_html: { class: 'form-control'} %>
  </div>
  <div class="col-sm-6">
    <%= f.input :max_students, input_html: { class: 'form-control'} %>
  </div>
  <div class="col-sm-12">
    <%= f.input :description, input_html: { class: 'form-control'} %>
  </div>
  <div class="col-sm-12">
    <%= f.input :price, input_html: { class: 'form-control'} %>
  </div>
  <div class="col-sm-12">
    <%= f.input :address, input_html: { id: 'user_input_autocomplete_address', class: 'form-control' } %>
  </div>
  <div class="col-sm-12">
    <%= f.input :street_number, input_html: { id: 'street_number', class: 'form-control' }, as: :hidden %>
  </div>
  <div class="col-sm-12">
    <%= f.input :street, input_html: { id: 'route', class: 'form-control' }, as: :hidden %>
  </div>
  <div class="col-sm-12">
    <%= f.input :city, input_html: { id: 'locality', class: 'form-control' }, as: :hidden %>
  </div>
  <div class="col-sm-12">
    <%= f.input :zip_code, input_html: { id: 'postal_code', class: 'form-control' }, as: :hidden %>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 text-center">
    <div class="data-status animated fadeInDown"></div> <!-- data submit status -->
  </div>
</div>
<div class="row">
  <div class="col-sm-12 text-center">
    <%= f.button :submit, class:'btn btn-lg btn-skin btn-radius margin-b-20' %>
  </div>
</div>
<% end %>


<% content_for(:js) do %>
<%= javascript_tag do %>
$(function () {
  $('#datetimepicker1').datetimepicker();
});
<% end %>
<% end %>

app/views/lessons/create.html.erb
<h1>Lessons#create</h1>
<p>Find me in app/views/lessons/create.html.erb</p>

app/views/lessons/edit.html.erb
<section id="home" class="home-newsletter">
    <div class="row no-margin">
        <div class="col-sm-12 center-title">
            <h2><i class="fa fa-file-text-o"></i> <%= t(".lesson", default: "Fiche de cours") %></h2>
        </div>
    </div>
</section>

<section id="contact" class="contact-section">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="wrapper-grey">
          <%= render 'form_lesson' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/lessons/my_index.html.erb
<h1><%= t('.my_lessons') %></h1>

<%= link_to t('.add_lesson'), new_lesson_path %>

<h3><%= t('.next_lessons') %></h3>

<% @lessons.where('start_date >= ?', DateTime.now).order(:start_date).each do |lesson| %>
  <%= link_to lesson.name, lesson_path(lesson) %>
  <%= lesson.start_date %>
  <%= lesson.end_date %>
  <%= lesson.status %>
  <%= link_to t('.edit_lesson'), edit_lesson_path(lesson) %>
  <% if lesson.status == 'confirmed' %>
    <%= link_to t('.cancel_lesson'), cancel_lesson_path(lesson) %> <br>
  <% else %>
    <%= link_to t('.reoffer_lesson'), edit_lesson_path(lesson) %> <br>
  <% end %>
<% end %>

<h3><%= t('.past_lessons') %></h3>

<% @lessons.where('start_date < ?', DateTime.now).order(:start_date).each do |lesson| %>
  <%= link_to lesson.name, lesson_path(lesson) %>
  <%= lesson.start_date %>
  <%= lesson.end_date %>
  <%= lesson.status %>
  <%= link_to t('.edit_lesson'), edit_lesson_path(lesson) %>
  <%= link_to t('.reoffer_lesson'), edit_lesson_path(lesson) %> <br>
<% end %>

app/views/lessons/new.html.erb
<section id="home" class="home-newsletter">
    <div class="row no-margin">
        <div class="col-sm-12 center-title">
            <h2><i class="fa fa-file-text-o"></i> <%= t(".lesson", default: "Fiche de cours") %></h2>
        </div>
    </div>
</section>

<section id="contact" class="contact-section">
  <div class="container">

    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="wrapper-grey">
          <%= render 'form_lesson' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/lessons/show.html.erb
<section id="home" class="home-newsletter">
    <div class="row no-margin">
        <div class="col-sm-12 center-title">
            <h2><i class="fa fa-file-text-o"></i> <%= t(".lesson", default: "Fiche de cours") %>
        </div>
    </div>
</section>

<section class="blog" id="search">
  <div class="container">

    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <div class="col-md-6" id="teacher-card">
            <div class="center-title">
              <%= link_to show_card_avatar(@lesson.teacher), teacher_path(@lesson.teacher)%>
            </div>
            <h3 class="text-center photo-padding red"><%= @lesson.teacher.first_name %></h3>
            <%= simple_form_for([@lesson.teacher, @message]) do |f| %>
            <%= f.error_notification %>
            <%= f.input :content, label: false, as: :text, placeholder:'Ecrire un message à ce professeur...', input_html: { class: 'message' } %>
        </div>

        <div class="col-md-6" id="description-card">
            <h3 class="home text-center red "><%= @lesson.name %></h3>

            <div class="list-group">
              <p class="list-group-item"> <i class="fa fa-calendar fa-lg red"></i>&nbsp; <%= @lesson.start_date.to_time.to_formatted_s(:short) %></p>
              <p class="list-group-item"><span class="red"><%= t('.places') %></span>&nbsp; <%= @lesson.max_students - @lesson.bookings.size %> / <%= @lesson.max_students %></p>
              <p class="list-group-item"><i class="fa fa-clock-o fa-lg red"></i>&nbsp; <%= @lesson.hours %> heures <% if @lesson.minutes != 0 %> <%= @lesson.minutes %> minutes <br> <% end %></p>

              <p class="list-group-item"><i class="fa fa-map-marker fa-lg red"></i>&nbsp; <%= @lesson.location_name %>
                <%= @lesson.street_number %><%= @lesson.address %>
                <%= @lesson.zip_code %><%= @lesson.city %>
              </p>
              <p class="list-group-item"><i class="fa fa-money fa-lg red" aria-hidden="true"></i>&nbsp; <%= humanized_money_with_symbol(@lesson.price) %></p>
              <p class="list-group-item"><span class="red">Description : </span><%= @lesson.description %></p>
            </div>
        </div>
      </div>
    </div>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
    <div class="col-md-6">
        <div class="text-center">
          <%= button_tag(type: 'submit', class: "btn btn-lg btn-greylight btn-radius") do %>
          <i class="fa fa-envelope-o"></i> Envoyer
          <% end %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <span class='text-center'>
          <% if @lesson.teacher == current_user %>
          <%= t('.user_cannot_be_teacher') %>
          <% else %>
          <%= form_tag lesson_bookings_path @lesson do %>
          <%= submit_tag t('.purchase'), class: 'btn btn-lg btn-radius btn-skin' %>
          <% end %>
          <% end %>
        </span>
      </div>
    </div>
  </div>
</div>
</section>


<!--
<div class="container padded">
  <div class="row">
      <div id="owl-news">

          <div class="item">
            <div class="col-md-12">

            <div class="text-center">
              <%= link_to show_card_avatar(@lesson.teacher), teacher_path(@lesson.teacher)%>
            </div>
            <h5 class="text-center photo-padding red"><%= @lesson.teacher.first_name %></h5>
                <%= simple_form_for([@lesson.teacher, @message]) do |f| %>
                <%= f.error_notification %>
                <%= f.input :content, label: false, as: :text, placeholder:'Ecrire un message à ce professeur...', input_html: { class: 'message' } %>
            </div>
          </div>
          </div>
          <div class="col-md-7">
            <blockquote class="w3-container w3-leftbar w3-light-grey">
            <h3 class="home text-center red "><%= @lesson.name %></h3>

              <div class="list-group">
                <h6 class="list-group-item"> <i class="fa fa-calendar fa-lg red"></i>&nbsp; <%= @lesson.start_date.to_time.to_formatted_s(:short) %></h6>
                <h6 class="list-group-item"><span class="red"><%= t('.places') %></span>&nbsp; <%= @lesson.max_students - @lesson.bookings.size %> / <%= @lesson.max_students %></h6>
                <h6 class="list-group-item"><i class="fa fa-clock-o fa-lg red"></i>&nbsp; <%= @lesson.hours %> heures <% if @lesson.minutes != 0 %> <%= @lesson.minutes %> minutes <br> <% end %></h6>

                <h6 class="list-group-item"><i class="fa fa-map-marker fa-lg red"></i>&nbsp; <%= @lesson.location_name %>
                <%= @lesson.street_number %><%= @lesson.address %>
                <%= @lesson.zip_code %><%= @lesson.city %>
                </h6>
                <h6 class="list-group-item"><i class="fa fa-money fa-lg red" aria-hidden="true"></i>&nbsp; <%= humanized_money_with_symbol(@lesson.price) %></h6>
                <h6 class="list-group-item"><span class="red">Description : </span><%= @lesson.description %></h6>
              </div>
            </blockquote>


          </div>

      </div>
  </div>

    <div class="row">
      <div id="owl-news">
        <div class="col-md-5">
          <div class="item">
            <div class="text-center">
              <%= button_tag(type: 'submit', class: "btn btn-default btn-radius text-center") do %>
                <i class="fa fa-envelope-o"></i> Envoyer
                <% end %>
              <% end %>
          </div>
        </div>
        <div class="col-md-7">
          <span class='text-center'>
          <% if @lesson.teacher == current_user %>
            <%= t('.user_cannot_be_teacher') %>
            <% else %>
            <%= form_tag lesson_bookings_path @lesson do %>
              <%= submit_tag t('.purchase'), class: 'btn btn-skin' %>
              <% end %>
          <% end %>
          </span>
        </div>
      </div>
    </div>
  </div>

 -->




<div id="map" style="width: 100%; height: 350px;"></div>

<% content_for(:js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: { scrollwheel: false }, internal: { id: 'map'} }, function(){
        markers = handler.addMarkers(<%= raw @marker.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(14);
      });
    })
  <% end %>
<% end %>

app/views/lessons/update.html.erb
<h1>Lessons#update</h1>
<p>Find me in app/views/lessons/update.html.erb</p>